version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "samtestappp319"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-z6c1mtfy8obt"
s3_prefix = "samtestappp319"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
